/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu.main;

import igu.compras.ComprasMainPanel;
import igu.inventario.InventoryMainPanel;
import igu.ventas.VentasMainPanel;
import java.awt.Color;

/**
 *
 * @author Asullom
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.comprasButton.setSelected(true);
        new ChangePanel(mainPanel, new ComprasMainPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menubar = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        ventasButton = new igu.util.buttons.TheButton();
        comprasButton = new igu.util.buttons.TheButton();
        inventoryButton = new igu.util.buttons.TheButton();
        dp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Salir");

        ventasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/img/collection.png"))); // NOI18N
        ventasButton.setText("VENTAS");
        ventasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ventasButtonMousePressed(evt);
            }
        });
        ventasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasButtonActionPerformed(evt);
            }
        });

        comprasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/img/market.png"))); // NOI18N
        comprasButton.setText("COMPRAS");
        comprasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comprasButtonMousePressed(evt);
            }
        });
        comprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasButtonActionPerformed(evt);
            }
        });

        inventoryButton.setText("INVENTARIO");
        inventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inventoryButtonMousePressed(evt);
            }
        });
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(comprasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(ventasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comprasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dp.setBackground(new java.awt.Color(204, 204, 204));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(mainPanel);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menubar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasButtonActionPerformed
        // TODO add your handling code here:
        new ChangePanel(mainPanel, new ComprasMainPanel());
        if (this.comprasButton.isSelected()) {
            this.comprasButton.setColorNormal(new Color(120, 152, 154));
            this.comprasButton.setColorHover(new Color(120, 152, 154));
            this.comprasButton.setColorPressed(new Color(120, 152, 154));
            
            this.ventasButton.setColorNormal(new Color(53, 172, 176));
            this.ventasButton.setColorHover(new Color(120, 152, 154));
            this.ventasButton.setColorPressed(new Color(120, 152, 154));

            this.inventoryButton.setColorNormal(new Color(53, 172, 176));
            this.inventoryButton.setColorHover(new Color(120, 152, 154));
            this.inventoryButton.setColorPressed(new Color(120, 152, 154));
            
          
        }
    }//GEN-LAST:event_comprasButtonActionPerformed

    private void comprasButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasButtonMousePressed
        // TODO add your handling code here:
        this.comprasButton.setSelected(true);
        this.inventoryButton.setSelected(false);
        this.ventasButton.setSelected(false);
    }//GEN-LAST:event_comprasButtonMousePressed

    private void ventasButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasButtonMousePressed
        // TODO add your handling code here:
        this.comprasButton.setSelected(false);
        this.inventoryButton.setSelected(false);
        this.ventasButton.setSelected(true);
    }//GEN-LAST:event_ventasButtonMousePressed

    private void ventasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasButtonActionPerformed
        // TODO add your handling code here:
       
         new ChangePanel(mainPanel, new VentasMainPanel());
        if (this.ventasButton.isSelected()) {
            this.comprasButton.setColorNormal(new Color(53, 172, 176));
            this.comprasButton.setColorHover(new Color(120, 152, 154));
            this.comprasButton.setColorPressed(new Color(120, 152, 154));
            
            this.ventasButton.setColorNormal(new Color(120, 152, 154));
            this.ventasButton.setColorHover(new Color(120, 152, 154));
            this.ventasButton.setColorPressed(new Color(120, 152, 154)); 
            
            this.inventoryButton.setColorNormal(new Color(53, 172, 176));
            this.inventoryButton.setColorHover(new Color(120, 152, 154));
            this.inventoryButton.setColorPressed(new Color(120, 152, 154));
        
    }//GEN-LAST:event_ventasButtonActionPerformed
    }
    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
         new ChangePanel(mainPanel, new InventoryMainPanel());
        if (this.inventoryButton.isSelected()) {
            this.comprasButton.setColorNormal(new Color(53, 172, 176));
            this.comprasButton.setColorHover(new Color(120, 152, 154));
            this.comprasButton.setColorPressed(new Color(120, 152, 154));
            
            this.ventasButton.setColorNormal(new Color(53, 172, 176));
            this.ventasButton.setColorHover(new Color(120, 152, 154));
            this.ventasButton.setColorPressed(new Color(120, 152, 154));      
            
            this.inventoryButton.setColorNormal(new Color(120, 152, 154));
            this.inventoryButton.setColorHover(new Color(120, 152, 154));
            this.inventoryButton.setColorPressed(new Color(120, 152, 154));
    }                    
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void inventoryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryButtonMousePressed
        // TODO add your handling code here:
        this.comprasButton.setSelected(false);
        this.inventoryButton.setSelected(true);
        this.ventasButton.setSelected(false);
    }//GEN-LAST:event_inventoryButtonMousePressed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private igu.util.buttons.TheButton comprasButton;
    private javax.swing.JPanel dp;
    private igu.util.buttons.TheButton inventoryButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menubar;
    private igu.util.buttons.TheButton ventasButton;
    // End of variables declaration//GEN-END:variables
}
